#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/531e9b28-46fb-4d5a-83ec-09e27b85cfe1
title: subject-demo
version: 1.0
protocols: [HTTPS]
mediaType: [application/json]

types:
  Subject:
    type: !include subject-post-schema.json
    description: this is a schema describing person

/v1.0/subjects:
  get:    
    responses:
      200:
        body:
          application/json:
            example: !include examples/subject.json
  
  post:
    description: Creates a bank account for the customer
    body:
      type: Subject
      example: !include examples/subject-post-request.json
    responses:
      201:
        headers:
          Location:
            description: URI pointing to the newly created student account
               